language: go
os: linux
dist: xenial

env:
  global:
    - upstream="armPelionEdge/maestro"
    - GOBIN="./bin"


# GoLang has an odd dependency management scheme.  Imports are hard-linked to
# their parent repos.  Forked repos therefore must either modify _all_ of their
# imports, or change their directory naming to match their parent.
#
# For reasons that I hope are obvious, we do the latter here.
install: 
  - |
    if [[ "${TRAVIS_REPO_SLUG}" != "${upstream}" ]]; then
      mkdir -p "../../${upstream}"
      mv * ".git" "../../${upstream}/"
      cd "../../${upstream}"
    fi
  

script: 
  # Build dependencies
  - ./build-deps.sh

  # Build maestro
  - ./build.sh

  # Run unit tests
  - cd "../../${upstream}"
  - > 
    (DEBUG=1 DEBUG2=1 ./build.sh;
    cd sysstats;
    LD_LIBRARY_PATH=../../maestro/vendor/github.com/armPelionEdge/greasego/deps/lib/ go test -v;
    cd ..;
    cd maestroConfig;
    LD_LIBRARY_PATH=../../maestro/vendor/github.com/armPelionEdge/greasego/deps/lib/ go test -v;
    cd ..;
    )
  
matrix:
  include:

    - name: "go v1.10"
      go: 1.10.x

    - name: "go v1.11"
      go: 1.11.x

    - name: "go v1.12"
      go: 1.12.x


